[target.'cfg(any(target_arch = "xtensa", target_arch = "riscv"))']
runner = "espflash flash --monitor"

[build]
rustflags = [
  "-C", "link-arg=-nostartfiles",
]

target = ["xtensa-esp32-none-elf", "xtensa-esp32s2-none-elf"]

[unstable]
build-std = ["core"]
